#pragma once

extern int torso;
extern int torsotexture;
extern int face;
extern int facetexture;
extern int head;
extern int headtexture;
extern int hair;
extern int hairtexture;
extern int legs;
extern int legstexture;
extern int hands;
extern int handstexture;
extern int feet;
extern int feettexture;
extern int eyes;
extern int eyestexture;
extern int accesories;
extern int accesoriestexture;
extern int accesoriessec;
extern int accesoriessectexture;
extern int textures;
extern int texturestexture;
extern int torsosec;
extern int torsosectexture;
extern int BailToSinglePlayerHotkey;
extern int AntiCrashCameraHotkey;
extern int SuicideHotkey;
extern int TeleportForward2mHotkey;
extern int MaxUpgradeVehicleHotKey;
extern int GodModeToggleHotkey;
extern int RepairAndCleanVehicleHotkey;
extern int TeleportToWaypointHotkey;
extern int RanksArray[8000];
extern void notifyleft(char* msg);
extern void TPto(Vector3 Coords);
extern int NumberKeyboard();
extern void clearanimnearbypeds();
extern void doAnimation(char* anim, char* animid);
extern void doAnimationNearbyPeds(char* anim, char* animid);
extern void PlayScenarioNearbyPeds(char* Scenario);
extern void attachobjects_allplayers(char* object);
extern void attachobjects2(char* object);